spring:
  application:
    name: spending-bff
server:
  port: 8081

clients:
  spending-manager:
    base-url: "http://localhost:8080"
    path-get-all: "/spendings"
    path-create: "/spent"
    path-get-id: "/spent/{id}"
    path-update: "/spent/{id}"